[project]
name = "cloud-run-etl-aemet"
version = "0.1.0"
description = "Extract data from API AEMET"
readme = "README.md"
requires-python = ">=3.11"
authors = [{name = "Robert Gavilanes", email = "r.gavilanes@altostratus.es"}]
dependencies = []

[tool.setuptools]
packages = ["cloud_run_etl_aemet"]


[tool.uv]
package = true
